---
title: 'Association of childhood obesity rates with local characteristics for Year 6 primary school children in England'
output: html_document
---
## Install all packages
```{r setup, include=FALSE,message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Install all packages
install.packages("janitor")
#Install mapping packages
install.packages("maptools")
install.packages(c("OpenStreetMap", "classInt"))
install.packages(c("RColorBrewer", "sp", "rgeos", 
                   "tmaptools", "sf", "downloader", "rgdal", 
                   "geojsonio"))
#Change path for java to ensure packages will load.
Sys.setenv(JAVA_HOME="")
install.packages("openxlsx")
install.packages("dplyr")
install.packages("plotly")
install.packages(c("sf", "tmap", "RSQLite", "tidyverse"), repos = "https://www.stats.bris.ac.uk/R/")
install.packages("assertive")
install.packages("naniar")
install.packages("spdep")
install.packages("car")
install.packages("caret")
install.packages("spatialreg")
install.packages("spgwr")
#Load all packages
devtools::install_github("rsquaredacademy/olsrr")
library(spatialreg)
library(spgwr)
library(car)
library(caret)
library(spdep)
library(tidyr)
library(olsrr)
library(car)
library(ggplot2)
library(corrplot)
library(janitor)
library(maptools)
library(RColorBrewer)
library(classInt)
library(OpenStreetMap)
library(sp)
library(rgeos)
library(tmap)
library(tmaptools)
library(sf)
library(rgdal)
library(geojsonio)
library(openxlsx)
library(plotly)
library(tidyverse)
library(dplyr)
library(assertive)
library(plyr)
library(naniar)
```

## SECTION 1: Data management

```{r include=FALSE,message=FALSE,warning=FALSE}
######Read in national child measurement data and convert to a data frame.
obesitydata<-read.csv("data/yr6_childmeasurement201819.csv")
obesitydata<-data.frame(obesitydata)
childdata<-obesitydata[-grep("^E1",obesitydata[,2]),]
#Data cleanse, remove empty rows and arbitrary records.
remove_empty(childdata, which = c("rows"))
childdata<- childdata %>% dplyr::filter(!(ONS.Code==""))
#Rename LA variable
names(childdata)[1] <- c("LA")
childdata<- childdata %>% dplyr::filter(!(LA=="ENGLAND1"))
class(childdata)
#check dataset
names(childdata)
summary(childdata)
#Rename ons code variable
names(childdata)[2] <- c("2011GSS_CODE")



#Keep obesity related variables to reduce size of file.
childdata<- childdata[,c( "LA","2011GSS_CODE","Obese_percent","overandobese_percent", "Severely.obese_percent", "Total.number.of.children")]    
#Change variables into numeric variables
childdata$Obese_percent_num <- as.numeric(childdata$"Obese_percent")
str(childdata)

childdata$Severely.obese_percent<- revalue(childdata$"Severely.obese_percent", c("x"="0"))
childdata$Severely.obese_percentnum <-as.numeric(paste((childdata$"Severely.obese_percent")))
#Create obesity rate variable.
childdata$obesity_rate<- childdata$Obese_percent_num +childdata$Severely.obese_percentnum
childdata<- childdata[,c( "LA","2011GSS_CODE","Obese_percent","overandobese_percent", "obesity_rate", "Total.number.of.children")]   


#NCMP data uses 2011 LA ecode, LA code changed for 2019, need to add in new code to allow IMD variables to be fully merged.
childdata$GSS_CODE<- (childdata$"2011GSS_CODE")
#New 2019 code: E06000058 - Bournemouth, Christchurch and Poole - new unitary authority instead of:
#Old code:E06000028	Bournemouth,E06000029	Poole,E07000048	Christchurch
childdata$GSS_CODE<- revalue(childdata$"GSS_CODE", c("E06000028"="E06000058","E06000029"="E06000058","E07000048"="E06000058"))

#New 2019 code:E06000059 - Dorset - new unitary authority - (Dorset county abolished)
#Old code:E07000049	East Dorset,E07000050	North Dorset,E07000051	Purbeck,E07000052	West Dorset,E07000053	Weymouth and Portland
childdata$GSS_CODE<- revalue(childdata$"GSS_CODE", c("E07000049"="E06000059","E07000050"="E06000059","E07000051"="E06000059",
                                                     "E07000052"="E06000059","E07000053"="E06000059"))


#New 2019 code:E07000244 - East Suffolk - new local authority district (Suffolk Coastal and Waveney districts abolished)
#Old code:E07000205	Suffolk Coastal,E07000206	Waveney
childdata$GSS_CODE<- revalue(childdata$"GSS_CODE", c("E07000205"="E07000244","E07000206"="E07000244"))


#New 2019 code:E07000245 - West Suffolk - new local authority district (Forest Heath and St Edmundsbury districts abolished)
#Old code:E07000201	Forest Heath,E07000204	St. Edmundsbury
childdata$GSS_CODE<- revalue(childdata$"GSS_CODE", c("E07000201"="E07000245","E07000204"="E07000245"))

#New 2019 code:E07000246 - Somerset West and Taunton - new local authority district (Taunton Deane and West Somerset districts abolished)
#Old code:E07000190	Taunton Deane,E07000191	West Somerset
childdata$GSS_CODE<- revalue(childdata$"GSS_CODE", c("E07000190"="E07000246","E07000191"="E07000246"))

#####Fast food shop density file
fastfood<-read.csv("data/fastfood_outlet.csv")
fastfood<-data.frame(fastfood)
is.na(fastfood) <- fastfood == "*"
fastfood$fast_food_density<-as.numeric(paste((fastfood$"Rate.per.100.000.population")))
#La code for this data is for 2018, change some of the codes to 2011 La code to allow full merge into main data.
#change E06000048	Northumberland to	E06000057
#change E07000097	East Hertfordshire	to	E07000242
#change E07000100	St Albans	to	E07000240
#change E07000101	Stevenage	to	E07000243
#change E07000104	Welwyn Hatfield	to	E07000241
#change E08000020	Gateshead	to	E08000037
fastfood$LA.code<- revalue(fastfood$"LA.code", c("E06000048"="E06000057"))
fastfood$LA.code<- revalue(fastfood$"LA.code", c("E07000097"="E07000242"))
fastfood$LA.code<- revalue(fastfood$"LA.code", c("E07000100"="E07000240"))
fastfood$LA.code<- revalue(fastfood$"LA.code", c("E07000101"="E07000243"))
fastfood$LA.code<- revalue(fastfood$"LA.code", c("E07000104"="E07000241"))
fastfood$LA.code<- revalue(fastfood$"LA.code", c("E08000020"="E08000037"))
names(fastfood)[2] <- c("2011GSS_CODE")
#Merge into main data.
childdata <- merge(x = childdata, y = fastfood, by = "2011GSS_CODE", all.x = TRUE)

#####Ethnicity data uses the 2011 ecode as well, merge in ethnicity data first.
ethnicity<-read.csv("data/census_ethnicity.csv")
ethnicity<-data.frame(ethnicity)
names(ethnicity)[3] <- c("2011GSS_CODE")
#Only keep variables of interest to reduce size of data.
ethnicity_por<- ethnicity[,c("2011GSS_CODE","Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..All.categories..Ethnic.group..measures..Value",
                             "Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..White..Total..measures..Value", 
                             "Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..Mixed.multiple.ethnic.group..Total..measures..Value",
                             "Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..Asian.Asian.British..Total..measures..Value",
                             "Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..Black.African.Caribbean.Black.British..Total..measures..Value",
                             "Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..Other.ethnic.group..Total..measures..Value")]


#Merge with main dataset
childdata2 <- merge(x = childdata, y = ethnicity_por, by = "2011GSS_CODE", all.x = TRUE)


#Summarise the ethnicity and obesity data for the unitary local authorites that were combined in 2019.
childdata2 <-data.frame(aggregate(. ~ GSS_CODE,childdata2, sum))

#Create percentage variables for each ethnic group.
childdata2$percent_white<- childdata2[[ "Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..White..Total..measures..Value"]]/childdata2[["Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..All.categories..Ethnic.group..measures..Value"]]
childdata2$percent_mix<- childdata2[["Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..Mixed.multiple.ethnic.group..Total..measures..Value"]]/childdata2[["Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..All.categories..Ethnic.group..measures..Value"]]
childdata2$percent_asian<- childdata2[["Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..Asian.Asian.British..Total..measures..Value"]]/childdata2[["Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..All.categories..Ethnic.group..measures..Value"]]
childdata2$percent_african<- childdata2[[ "Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..Black.African.Caribbean.Black.British..Total..measures..Value"]]/childdata2[["Sex..All.persons..Age..Age.0.to.24..Ethnic.Group..All.categories..Ethnic.group..measures..Value"]]




#New 2019 code: E06000058 - Bournemouth, Christchurch and Poole - new unitary authority instead of:
#Old code:E06000028	Bournemouth,E06000029	Poole,E07000048	Christchurch

childdata2$obesity_rate<- with(childdata2, ifelse(GSS_CODE=='E06000058',(childdata2$obesity_rate)/3,obesity_rate))
childdata2$fast_food_density<- with(childdata2, ifelse(GSS_CODE=='E06000058',(childdata2$fast_food_density)/3,fast_food_density))

#New 2019 code:E06000059 - Dorset - new unitary authority - (Dorset county abolished)
#Old code:E07000049	East Dorset,E07000050	North Dorset,E07000051	Purbeck,E07000052	West Dorset,E07000053	Weymouth and Portland

childdata2$obesity_rate<- with(childdata2, ifelse(GSS_CODE=='E06000059',(childdata2$obesity_rate)/5,obesity_rate))
childdata2$fast_food_density<- with(childdata2, ifelse(GSS_CODE=='E06000059',(childdata2$fast_food_density)/5,fast_food_density))
#New 2019 code:E07000244 - East Suffolk - new local authority district (Suffolk Coastal and Waveney districts abolished)
#Old code:E07000205	Suffolk Coastal,E07000206	Waveney
childdata2$obesity_rate<- with(childdata2, ifelse(GSS_CODE=='E07000244',(childdata2$obesity_rate)/2,obesity_rate))
childdata2$fast_food_density<- with(childdata2, ifelse(GSS_CODE=='E07000244',(childdata2$fast_food_density)/2,fast_food_density))
#New 2019 code:E07000245 - West Suffolk - new local authority district (Forest Heath and St Edmundsbury districts abolished)
#Old code:E07000201	Forest Heath,E07000204	St. Edmundsbury
childdata2$obesity_rate<- with(childdata2, ifelse(GSS_CODE=='E07000245',(childdata2$obesity_rate)/2,obesity_rate))
childdata2$fast_food_density<- with(childdata2, ifelse(GSS_CODE=='E07000245',(childdata2$fast_food_density)/2,fast_food_density))

#New 2019 code:E07000246 - Somerset West and Taunton - new local authority district (Taunton Deane and West Somerset districts abolished)
#Old code:E07000190	Taunton Deane,E07000191	West Somerset
childdata2$obesity_rate<- with(childdata2, ifelse(GSS_CODE=='E07000246',(childdata2$obesity_rate)/2,obesity_rate))
childdata2$fast_food_density<- with(childdata2, ifelse(GSS_CODE=='E07000246',(childdata2$fast_food_density)/2,fast_food_density))

######Read in multiple excel tabs for the imd data.

IMD_income <- read.xlsx('data/IMD2019.xlsx',sheet=3)
IMD_employ <- read.xlsx('data/IMD2019.xlsx',sheet=4)
IMD_edu <- read.xlsx('data/IMD2019.xlsx',sheet=5)
IMD_health <- read.xlsx('data/IMD2019.xlsx',sheet=6)
IMD_crime <- read.xlsx('data/IMD2019.xlsx',sheet=7)
IMD_barriers <- read.xlsx('data/IMD2019.xlsx',sheet=8)
IMD_living <- read.xlsx('data/IMD2019.xlsx',sheet=9)
IMD_idaci <- read.xlsx('data/IMD2019.xlsx',sheet=10)
#Put data into data frames.

IMD_income <- data.frame(IMD_income)
IMD_employ <- data.frame(IMD_employ)
IMD_edu <- data.frame(IMD_edu)
IMD_health <- data.frame(IMD_health)
IMD_crime <- data.frame(IMD_crime)
IMD_barriers <- data.frame(IMD_barriers)
IMD_living <- data.frame(IMD_living)
IMD_idaci <- data.frame(IMD_idaci)

#Rename ons code variable
names(childdata)[2] <- c("GSS_CODE")
names(IMD_income)[1] <- c("GSS_CODE")
names(IMD_employ)[1] <- c("GSS_CODE")
names(IMD_edu)[1] <- c("GSS_CODE")
names(IMD_health)[1] <- c("GSS_CODE")
names(IMD_crime)[1] <- c("GSS_CODE")
names(IMD_barriers)[1] <- c("GSS_CODE")
names(IMD_living)[1] <- c("GSS_CODE")
names(IMD_idaci)[1] <- c("GSS_CODE")
#Remove duplicate variables in these files.
IMD_income <-within(IMD_income, rm("Local.Authority.District.name..2019."))
IMD_employ <-within(IMD_employ , rm("Local.Authority.District.name..2019."))
IMD_edu <-within(IMD_edu, rm("Local.Authority.District.name..2019."))
IMD_health <-within(IMD_health, rm("Local.Authority.District.name..2019."))
IMD_crime <-within(IMD_crime, rm("Local.Authority.District.name..2019."))
IMD_barriers <-within(IMD_barriers, rm("Local.Authority.District.name..2019."))
IMD_living <-within(IMD_living, rm("Local.Authority.District.name..2019."))
IMD_idaci <-within(IMD_idaci, rm("Local.Authority.District.name..2019."))




#Merge the datasets
childdata2 <- merge(x = childdata2, y = IMD_income, by = "GSS_CODE", all.x = TRUE)
childdata2 <- merge(x = childdata2, y = IMD_employ, by = "GSS_CODE", all.x = TRUE)
childdata2 <- merge(x = childdata2, y = IMD_edu, by = "GSS_CODE", all.x = TRUE)
childdata2 <- merge(x = childdata2, y = IMD_health, by = "GSS_CODE", all.x = TRUE)
childdata2 <- merge(x = childdata2, y = IMD_crime, by = "GSS_CODE", all.x = TRUE)
childdata2 <- merge(x = childdata2, y = IMD_barriers, by = "GSS_CODE", all.x = TRUE)
childdata2 <- merge(x = childdata2, y = IMD_living, by = "GSS_CODE", all.x = TRUE)
childdata2 <- merge(x = childdata2, y = IMD_idaci, by = "GSS_CODE", all.x = TRUE)



#Physical activity data
activity <- read.xlsx('data/childactivity.xlsx',sheet=1)
activity<-data.frame(activity)
exercise<- activity[,c("La","GSS_CODE","X60minplus_Rate....","fairly_active_Rate....","Less_active_Rate....")]
is.na(exercise) <- exercise == "^"
is.na(exercise) <- exercise == "*"
exercise$active_rate <-as.numeric(paste((exercise$"X60minplus_Rate....")))
exercise$fairly_active_rate <-as.numeric(paste((exercise$"fairly_active_Rate....")))
exercise$less_active_rate <-as.numeric(paste((exercise$"Less_active_Rate....")))
exercise<- exercise[,c("La","GSS_CODE","active_rate", "fairly_active_rate","less_active_rate")]
#Merge with main dataset
childdata2 <- merge(x = childdata2, y =exercise, by = "GSS_CODE", all.x = TRUE)

#Keep only relavent IMD variables. We will use the score variables.
childdata2<- childdata2[,c("GSS_CODE","obesity_rate","fast_food_density","active_rate",
                           "percent_white",                                                                                  
                           "percent_mix",                                                                                   
                           "percent_asian",                                                                                  
                           "percent_african",
                           "Income...Average.rank",
                           "Employment...Average.rank",
                           "Education..Skills.and.Training...Average.rank",
                           "Health.Deprivation.and.Disability...Average.rank",
                           "Crime...Average.rank",
                           "Barriers.to.Housing.and.Services...Average.rank",
                           "Living.Environment...Average.rank",
                           "IDACI...Average.rank",
                           "Income...Average.score",
                           "Employment...Average.score",
                           "Education..Skills.and.Training...Average.score",
                           "Health.Deprivation.and.Disability...Average.score",
                           "Crime...Average.score",
                           "Barriers.to.Housing.and.Services...Average.score",
                           "Living.Environment...Average.score",
                           "IDACI...Average.score",
                           "fairly_active_rate","less_active_rate" )]
names(childdata2)
#Rename variables with clearer names.


names(childdata2)[3] <- "Density of fast food outlets"
names(childdata2)[4] <- "Active rate"
names(childdata2)[5] <- "Percentage of White children"
names(childdata2)[6] <- "Percentage of Mixed children"
names(childdata2)[7] <- "Percentage of Asian children"
names(childdata2)[8] <- "Percentage of African children"
names(childdata2)[17] <- "IMD income average score"
names(childdata2)[18] <- "IMD employment average score"
names(childdata2)[19] <- "IMD education average score"
names(childdata2)[20] <- "IMD health average score"
names(childdata2)[21] <- "IMD crime average score"
names(childdata2)[22] <- "IMD housing average score"
names(childdata2)[23] <- "IMD living average score"
names(childdata2)[24] <- "IMD IDACI average score"
names(childdata2)[25] <- "Fairly active rate"
names(childdata2)[26] <- "Less active rate"

```
## SECTION 2: Regression analysis

```{r include=FALSE,message=FALSE,warning=FALSE}

```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
